drm/bridge: synopsys: Fixes compilation errors when cec core is not compiled
Fix error: implicit declaration of function 'cec_queue_pin_hpd_event'.

Fixes: 5fe797153df8 ("drm: bridge: dw-hdmi: Support report cec hpd")
Change-Id: I4ddae31d5b72b17fdd33fbc28ca454dc57377f74
Signed-off-by: Algea Cao <algea.cao@rock-chips.com>
Signed-off-by: Songjun Li <lisongjun@radxa.com>