UBUNTU: SAUCE: (no-up) apusys: Include header file from correct place
Correct them since the header file is located at below place.

ubuntu/mtk-apusys-driver/power/apu_top_entry.h

Otherwise, we can see below build issues.

./ubuntu/mtk-apusys-driver/power/3.0/inc/apu_top.h:21:10: fatal error: apu_top_entry.h: No such file or directory
   21 | #include "apu_top_entry.h"
      |          ^~~~~~~~~~~~~~~~~

ubuntu/mtk-apusys-driver/power/3.0/aputop_drv.c:22:10: fatal error: apu_top_entry.h: No such file or directory
   22 | #include <apu_top_entry.h>
      |          ^~~~~~~~~~~~~~~~~

ubuntu/mtk-apusys-driver/power/3.0/apu_devfreq_cooling.c:20:10: fatal error: apu_top_entry.h: No such file or directory
   20 | #include <apu_top_entry.h>
      |          ^~~~~~~~~~~~~~~~~

Signed-off-by: Guoqing Jiang <guoqing.jiang@canonical.com>
Signed-off-by: Jian Hui Lee <jianhui.lee@canonical.com>