mdla: Use get_random_u32 instead of get_random_int
Fix the following build error when build with mtk-v6.6 kernel:

error: implicit declaration of function 'get_random_int'

Change-Id: Ie79a53976fe670406dbb940480bc998d318e0a58
Signed-off-by: Pablo Sun <pablo.sun@mediatek.com>
Signed-off-by: Guoqing Jiang <guoqing.jiang@canonical.com>
Signed-off-by: Jian Hui Lee <jianhui.lee@canonical.com>