UPSTREAM: wifi: mt76: mt7915: fix an uninitialized variable bug
Smatch complains that:

    ubuntu/mtk-mt76/mt7915/mac.c:428 mt7915_mac_fill_rx()
    error: uninitialized symbol 'msta'.

It looks like this was supposed to be initialized to NULL.

Fixes: 0880d40871d1 ("mt76: connac: move mt76_connac2_reverse_frag0_hdr_trans in mt76-connac module")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit b5ee771c84082b4e54cc39d9d9a2dd239e4f6b86)

BUG=b:178754244
TEST=emerge-corsola sys-kernel/chromeos-kernel-5_15;

Signed-off-by: Linux Patches Robot <linux-patches-robot@chromeos-missing-patches.google.com.iam.gserviceaccount.com>
Change-Id: Iaa14c4190d0509cc08582ffb37b56cf5e841b762
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3959157
Reviewed-by: David Ruth <druth@chromium.org>
Commit-Queue: David Ruth <druth@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
Tested-by: David Ruth <druth@chromium.org>
Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>