UBUNTU: SAUCE: (no-up) GENIO: clk: mediatek: Fix mtk_clk_fixup_divider()
When switching to the common clock framework, the
mtk_clk_fixup_divider() function made incorrect usage of the
clk_hw_register() function. The function returns an error status as an
int, while the caller expects it to return a struct clk_hw pointer. This
breaks in obvious ways, and is even flagged with a compiler warning:

drivers/clk/mediatek/clk-mtk.c: In function ‘mtk_clk_fixup_divider’:
drivers/clk/mediatek/clk-mtk.c:557:12: error: assignment to ‘struct clk_hw *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  557 |         hw = clk_hw_register(NULL, &fixup_div->divider.hw);
      |            ^

Fix it.

Change-Id: I2e6a303b0bc318eaa8fcbfad05d2554e98d43464
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Signed-off-by: Jian Hui Lee <jianhui.lee@canonical.com>