FIXUP: GENIO: ASoC: mediatek: Fix accdet support for mt8390-evk and mt8395-evk
To prevent build failures when building the BSP image, ensure that
SND_SOC_MT6359_ACCDET is selected when SND_SOC_MT8390_EVK or
SND_SOC_MT8395_EVK is enabled.

This commit resolves the issue of build failure occurring with the
log: "undefined reference to `mt6359_accdet_enable_jack_detect'".

With this change, accdet support will be enabled by default on
mt8390-evk and mt8395-evk.

fixes: 98ce86630c29 ("GENIO: ASoC: mediatek: mt8188: Add headset
jack detect support for mt8390-evk")
fixes: 962b69a82d8e ("GENIO: ASoC: mediatek: mt8195: Add headset
jack detect support for mt8395-evk")
Change-Id: I81041101497b5558881009144668e55f2fd704f0
Signed-off-by: Zoran Zhan <zoran.zhan@mediatek.com>
Signed-off-by: Guoqing Jiang <guoqing.jiang@canonical.com>
Signed-off-by: Jian Hui Lee <jianhui.lee@canonical.com>